/// <reference types="expo/types" />

// NOTE: This file should not be edited and is not part of the '.' project.
// This file is generated by 'expo'.
// To regenerate this file, run 'npx expo prebuild --clean'.
// (See https://docs.expo.dev/guides/typescript/#expos-typescript-declarations)

declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_API_URL: string;
    EXPO_PUBLIC_RAZORPAY_KEY_ID: string;
  }
}
